version: '3.8'

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: [ "sh", "-c", "yarn build && yarn prisma generate && yarn prisma db push && yarn start" ]
