version: "3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2345:2345"
    volumes:
      - ".:/usr/src/app"
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dinopoll
    restart: always
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinopoll
    volumes:
      - "db_volume:/var/lib/postgresql/data"
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "3002:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dinopoll?sslmode=disable
    depends_on:
      - db
volumes:
  db_volume:
